### ISSUE TITLE
Whitelisting required???

### ISSUE THREAD

**Issue by samsonpaul87** [android-pay/s2ap-quickstart-android#3]
Do I need to whitelist the credentials. Or can I run the sample code as it is?

I have updated the Loyalty Wallet Object with the provided value. When click on 'Save to Pay' button Iam receiving the following error. Please help.

- 08-09 14:22:07.614 2978-4068/? E/Volley: [205] BasicNetwork.performRequest: 
Unexpected response code 400 for 
https://wallet.google.com/payments/apis/instantbuy/android/v1/createWalletObjects 
08-09 14:22:07.614 2978-4091/? E/ServerConnection: Exception sending Volley 
request 
java.util.concurrent.ExecutionException: com.android.volley.ClientError 
at 
com.android.volley.toolbox.RequestFuture.a(:com.google.android.gms@12874026@12.8.74 
(040700-204998136):4) 
at 
com.android.volley.toolbox.RequestFuture.get(:com.google.android.gms@12874026@12.8.74 
(040700-204998136):1) 
at aqro.a(:com.google.android.gms@12874026@12.8.74 
(040700-204998136):32) 
at aqro.a(:com.google.android.gms@12874026@12.8.74 
(040700-204998136):28) 
at arjy.a(:com.google.android.gms@12874026@12.8.74 
(040700-204998136):8) 
at arjs.a(:com.google.android.gms@12874026@12.8.74 
(040700-204998136):32) 
at araa.a(:com.google.android.gms@12874026@12.8.74 
(040700-204998136):5) 
at arjr.a(:com.google.android.gms@12874026@12.8.74 
(040700-204998136):4) 
at arkb.a(:com.google.android.gms@12874026@12.8.74 
(040700-204998136):2) 
at arjl.a(Unknown Source:2) 
at arjp.a(:com.google.android.gms@12874026@12.8.74 
(040700-204998136):1) 
at wde.a(:com.google.android.gms@12874026@12.8.74 
(040700-204998136):3) 
at cbd.onTransact(:com.google.android.gms@12874026@12.8.74 
(040700-204998136):6) 
at arjl.onTransact(Unknown Source:0) 
at android.os.Binder.transact(Binder.java:627) 
at deg.onTransact(:com.google.android.gms@12874026@12.8.74 
(040700-204998136):3) 
at android.os.Binder.execTransact(Binder.java:697) 
Caused by: com.android.volley.ClientError 
at 
com.android.volley.toolbox.BasicNetwork.performRequest(:com.google.android.gms@12874026@12.8.74 
(040700-204998136):42) 
at pgk.performRequest(:com.google.android.gms@12874026@12.8.74 
(040700-204998136):17) 
at 
com.android.volley.NetworkDispatcher.a(:com.google.android.gms@12874026@12.8.74 
(040700-204998136):7) 
at 
com.android.volley.NetworkDispatcher.run(:com.google.android.gms@12874026@12.8.74 
(040700-204998136):2) 
08-09 14:22:07.618 6057-6057/? E/PaymentServiceResponseH: Unknown 
ServerResponse type=1

**Comment by ncalteen** [comment]
Hello,

My apologies, this repository is being deprecated. Please refer to the following repositories going forward. If there is anything you would like assistance with, please feel free to submit an issue.

* [google-pay/android-quickstart](https://github.com/google-pay/android-quickstart)
* [google-pay/wallet-samples](https://github.com/google-pay/wallet-samples)
